// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEUFevoTs38GMvyOzvGwX1DjmsKHvPLqQ',
    appId: '1:831544094300:web:f2227c22daddefb9bb8099',
    messagingSenderId: '831544094300',
    projectId: 'bill-app-4eb84',
    authDomain: 'bill-app-4eb84.firebaseapp.com',
    storageBucket: 'bill-app-4eb84.firebasestorage.app',
    measurementId: 'G-6NT7FS40VK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyNPeMazpeidBviyIJrXYhQx6toAVjBIY',
    appId: '1:831544094300:android:1cc0a5ae0f4fe18fbb8099',
    messagingSenderId: '831544094300',
    projectId: 'bill-app-4eb84',
    storageBucket: 'bill-app-4eb84.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7_e-GQIqes0mhSvlfvpfq1TswEJPH098',
    appId: '1:831544094300:ios:25d87f09746ba5f0bb8099',
    messagingSenderId: '831544094300',
    projectId: 'bill-app-4eb84',
    storageBucket: 'bill-app-4eb84.firebasestorage.app',
    androidClientId: '831544094300-4jphc2ov2b6tl6qrooe1vjprmc6nrfl4.apps.googleusercontent.com',
    iosClientId: '831544094300-c3s7tgltafrnjsc8f75hjp0l8jm9uak3.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7_e-GQIqes0mhSvlfvpfq1TswEJPH098',
    appId: '1:831544094300:ios:25d87f09746ba5f0bb8099',
    messagingSenderId: '831544094300',
    projectId: 'bill-app-4eb84',
    storageBucket: 'bill-app-4eb84.firebasestorage.app',
    androidClientId: '831544094300-4jphc2ov2b6tl6qrooe1vjprmc6nrfl4.apps.googleusercontent.com',
    iosClientId: '831544094300-c3s7tgltafrnjsc8f75hjp0l8jm9uak3.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEUFevoTs38GMvyOzvGwX1DjmsKHvPLqQ',
    appId: '1:831544094300:web:04ef9d22252b5452bb8099',
    messagingSenderId: '831544094300',
    projectId: 'bill-app-4eb84',
    authDomain: 'bill-app-4eb84.firebaseapp.com',
    storageBucket: 'bill-app-4eb84.firebasestorage.app',
    measurementId: 'G-ZW0QRTS23E',
  );
}
